name: ml_text_cleaner
description: A powerful and extensible text cleaning library for Dart and Flutter.
version: 0.1.0
homepage: https://github.com/CelkMehmett/ml_text_cleaner
repository: https://github.com/CelkMehmett/ml_text_cleaner
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  characters: ^1.3.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
